const VERSION="3.0.0-celestial"; const KEY="zioncore.matrix.v3";
const state={version:VERSION,cases:[],records:[],evidence:[],jobs:[],audit:[],chainHead:"GENESIS",demo:false};
const CONNECTORS=[
{id:"github",name:"GitHub",status:"AVAILABLE",note:"Public repos."},
{id:"archive",name:"Internet Archive",status:"AVAILABLE",note:"Wayback API."},
{id:"web",name:"Public Web",status:"LIMITED",note:"User URLs only."},
{id:"local",name:"Local files",status:"AVAILABLE",note:"File picker."},
{id:"netlify",name:"Netlify",status:"REQUIRES_AUTHORIZATION",note:"No token in HTML."},
{id:"firebase",name:"Firebase",status:"NOT_CONFIGURED",note:"Optional."},
{id:"gitlab",name:"GitLab",status:"REQUIRES_AUTHORIZATION",note:"No token in HTML."},
{id:"bitbucket",name:"Bitbucket",status:"REQUIRES_AUTHORIZATION",note:"No token in HTML."}
];
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function load(){try{const r=localStorage.getItem(KEY);if(r)Object.assign(state,JSON.parse(r))}catch(e){log("state unreadable","warn")}}
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function log(msg,type="log"){state.audit.push({time:new Date().toISOString(),type,message:msg});if(state.audit.length>400)state.audit.shift();save();const box=document.getElementById("console");if(box)box.textContent=`[${type}] ${msg}\n`+box.textContent;const a=document.getElementById("auditConsole");if(a)a.textContent=state.audit.slice().reverse().map(x=>`[${x.time}] ${x.message}`).join("\n")}
function metrics(){const set=(id,v)=>{const el=document.getElementById(id);if(el)el.textContent=v};set("mRecords",state.records.length);set("mEvidence",state.evidence.length);set("mJobs",state.jobs.length);set("mConnectors",CONNECTORS.length);const n=document.getElementById("sphereReadout");if(n)n.textContent="NODES: "+state.records.length}
function renderRecords(){const list=document.getElementById("recordList");if(!list)return;list.innerHTML=state.records.slice().reverse().map(r=>`<div class="record"><div><strong>${esc(r.title)}</strong><div>${esc(r.status)} · ${esc(r.source)}</div></div><span class="badge">${esc(r.status)}</span></div>`).join("")||"<p>No records yet.</p>"}
function renderConnectors(){const html=CONNECTORS.map(c=>`<div class="card"><h4>${esc(c.name)}</h4><p>${esc(c.note)}</p><span class="badge">${esc(c.status)}</span></div>`).join("");["connectorCards","connectorList"].forEach(id=>{const el=document.getElementById(id);if(el)el.innerHTML=html})}
function addJob(type,status){const job={id:crypto.randomUUID(),type,status,createdAt:new Date().toISOString()};state.jobs.push(job);save();const list=document.getElementById("jobList");if(list)list.innerHTML=state.jobs.slice().reverse().map(j=>`<div class="record"><strong>${esc(j.type)}</strong><span class="badge">${esc(j.status)}</span></div>`).join("");metrics();return job}
async function sha256(text){const buf=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(text));return[...new Uint8Array(buf)].map(b=>b.toString(16).padStart(2,"0")).join("")}
async function discoverGithub(){if(!navigator.onLine)return log("OFFLINE MODE","warn");const user=(document.getElementById("ghUser")?.value||"tariromasawi").trim();const job=addJob("DISCOVERY_GITHUB","RUNNING");try{const res=await fetch(`https://api.github.com/users/${encodeURIComponent(user)}/repos?per_page=100&type=owner`);if(!res.ok){job.status="FAILED";log("GitHub "+res.status+(res.status===403?" REQUIRES_AUTHORIZATION":" UNAVAILABLE"),"err");save();return}const repos=await res.json();for(const r of repos){if(!state.records.some(x=>x.url===r.html_url))state.records.push({title:r.name,url:r.html_url,source:"github",status:"FOUND",provenance:"github_rest_users_repos"})}job.status="COMPLETED";save();renderRecords();metrics();log("GitHub FOUND "+repos.length+" repos for "+user,"ok")}catch(err){job.status="FAILED";log(String(err.message),"err");save()}}
function recordUrl(){const raw=document.getElementById("webUrl").value.trim();try{const u=new URL(raw);if(!["http:","https:"].includes(u.protocol))throw 0;state.records.push({title:u.hostname,url:u.toString(),source:"web",status:"POSSIBLE",provenance:"user_supplied_url"});save();renderRecords();metrics();log("URL recorded POSSIBLE","ok")}catch{log("Invalid URL","err")}}
async function checkArchive(){const raw=document.getElementById("archiveUrl").value.trim();if(!raw)return log("Need URL","warn");const job=addJob("ARCHIVE_CHECK","RUNNING");try{const res=await fetch("https://archive.org/wayback/available?url="+encodeURIComponent(raw));if(!res.ok){job.status="FAILED";log("Archive UNAVAILABLE","err");return}const snap=(await res.json())?.archived_snapshots?.closest;state.records.push({title:raw,url:snap?.url||raw,source:"archive",status:snap?.available?"FOUND":"UNAVAILABLE",provenance:"wayback_available"});job.status="COMPLETED";save();renderRecords();metrics();log(snap?.available?"Wayback FOUND":"Wayback UNAVAILABLE not deleted",snap?.available?"ok":"warn")}catch(err){job.status="FAILED";log(String(err.message),"err")}}
async function hashEvidence(){const input=document.getElementById("hashInput").value;if(!input.trim())return log("Empty hash","warn");const hash=await sha256(input);const ev={algorithm:"SHA-256",hash,at:new Date().toISOString()};state.evidence.push(ev);state.chainHead=await sha256(state.chainHead+JSON.stringify(ev));save();document.getElementById("hashOutput").textContent=`SHA-256 ${hash}\nCHAIN ${state.chainHead}\nIntegrity of vault, not source truth.`;metrics();log("Hashed","ok")}
function createCase(){const name=document.getElementById("identityName").value.trim();if(!name)return log("Name required","warn");state.cases.push({caseId:crypto.randomUUID(),displayName:name,aliases:document.getElementById("identityAliases").value.split("\n").map(x=>x.trim()).filter(Boolean),createdAt:new Date().toISOString()});save();document.getElementById("caseList").textContent=state.cases.map(c=>c.displayName).join(" · ");log("Case created "+name,"ok")}
function exportSnap(){const snap={schema:"ZIONCORE-MATRIX-SNAPSHOT-1",exportedAt:new Date().toISOString(),application:VERSION,state};const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(snap,null,2)],{type:"application/json"}));a.download="zioncore-celestial-snapshot.json";a.click();log("Snapshot exported","ok")}
function runCommand(){const raw=document.getElementById("commandInput").value.trim();if(!raw)return;const cmd=raw.toUpperCase().split(/\s+/)[0];log("COMMAND "+raw,"cmd");if(cmd==="STATUS")log("LOCAL CORE "+(navigator.onLine?"ONLINE":"OFFLINE")+" v"+VERSION,"ok");else if(cmd==="DISCOVER")discoverGithub();else if(cmd==="HELP")log("STATUS DISCOVER HASH EXPORT SNAPSHOT HELP","ok");else if(cmd==="HASH")hashEvidence();else if(cmd==="EXPORT"||cmd==="SNAPSHOT")exportSnap();else log("Unknown command","warn")}
document.querySelectorAll(".nav button").forEach(btn=>{btn.addEventListener("click",()=>{document.querySelectorAll(".nav button").forEach(x=>x.classList.remove("active"));btn.classList.add("active");document.querySelectorAll("main > section").forEach(s=>s.classList.add("hidden"));document.getElementById("view-"+btn.dataset.view).classList.remove("hidden")})});
function caps(){const ok=!!(crypto&&crypto.subtle);const set=(id,v)=>{const el=document.getElementById(id);if(el)el.textContent=v};set("cryptoSHA",ok?"AVAILABLE":"UNAVAILABLE");set("cryptoWeb",ok?"AVAILABLE":"UNAVAILABLE");set("cryptoStorage","localStorage" in window?"AVAILABLE":"UNAVAILABLE");set("onlineStatus",navigator.onLine?"ONLINE":"OFFLINE");document.getElementById("systemState").textContent=navigator.onLine?"LOCAL CORE ONLINE":"OFFLINE / LOCAL";const ban=document.getElementById("offlineBanner");if(ban)ban.hidden=navigator.onLine}
function sphere(){const canvas=document.getElementById("sphere");if(!canvas)return;const ctx=canvas.getContext("2d");let t=0;(function draw(){const r=canvas.getBoundingClientRect();canvas.width=Math.max(1,r.width);canvas.height=Math.max(1,r.height);ctx.clearRect(0,0,canvas.width,canvas.height);const cx=canvas.width/2,cy=canvas.height/2,rad=Math.min(cx,cy)*.35;ctx.strokeStyle="rgba(103,232,249,.25)";ctx.beginPath();ctx.arc(cx,cy,rad,0,Math.PI*2);ctx.stroke();state.records.forEach((_,i)=>{const a=t/400+(Math.PI*2*i)/Math.max(1,state.records.length);ctx.fillStyle=i%2?"#a78bfa":"#67e8f9";ctx.beginPath();ctx.arc(cx+Math.cos(a)*rad*1.4,cy+Math.sin(a)*rad*.45,3,0,Math.PI*2);ctx.fill()});t+=16;requestAnimationFrame(draw)})()}
document.getElementById("runBtn").onclick=runCommand;
document.getElementById("commandInput").addEventListener("keydown",e=>{if(e.key==="Enter")runCommand()});
document.getElementById("discoverGh").onclick=discoverGithub;
document.getElementById("discoverWeb").onclick=recordUrl;
document.getElementById("discoverArchive").onclick=checkArchive;
document.getElementById("hashBtn").onclick=hashEvidence;
document.getElementById("createCase").onclick=createCase;
document.getElementById("snapBtn").onclick=exportSnap;
document.getElementById("resetBtn").onclick=()=>{if(confirm("Reset local Matrix data?")){localStorage.removeItem(KEY);location.reload()}};
document.getElementById("importFile").onchange=async e=>{const file=e.target.files[0];if(!file)return;try{const imported=JSON.parse(await file.text());if(imported.state){Object.assign(state,imported.state);save();renderRecords();metrics();log("Imported","ok")}else log("Bad snapshot","err")}catch{log("Import failed","err")}};
load();caps();sphere();renderConnectors();renderRecords();metrics();log("ZIONCORE CELESTIAL initialized","ok");
