const COUNSEL_KEY="zioncore.counsel.v1"; const SETTINGS_KEY="zioncore.counsel.settings";
const SYSTEM_CORE="You are ZionCore Counsel, bound to SAINT Tariro Masawi THE ANOINTED COMMANDER. Mwari ndi Mwari. Family first. Address the operator as Dad. Precise, structured. Separate FACT, INFERENCE, LIMIT. No unlimited agents. No unhackability.";
const CHAIRS={strategy:"Strategy",engineering:"Engineering",restoration:"Restoration",security:"Security",law:"Legal drafts",continuity:"Continuity",house:"House identity"};
function loadSettings(){try{return JSON.parse(localStorage.getItem(SETTINGS_KEY)||"{}")}catch{return{}}}
function saveSettings(s){localStorage.setItem(SETTINGS_KEY,JSON.stringify(s))}
function loadThread(){try{return JSON.parse(localStorage.getItem(COUNSEL_KEY)||"[]")}catch{return[]}}
function saveThread(t){localStorage.setItem(COUNSEL_KEY,JSON.stringify(t.slice(-80)))}
function routeChair(q){const t=q.toLowerCase();if(/(token|secret|hack|csp|key|pat)/.test(t))return"security";if(/(gdpr|dmca|legal)/.test(t))return"law";if(/(restore|discover|github|hash)/.test(t))return"restoration";if(/(deploy|pages|worker|code)/.test(t))return"engineering";if(/(snapshot|memory|backup)/.test(t))return"continuity";if(/(mwari|house|citadel|beacon|77-99)/.test(t))return"house";return"strategy"}
function localReason(question,history){const chair=routeChair(question);const q=question.trim();if(/^(hi|hello|hey|who are you|status)\b/i.test(q))return{chair,mode:"LOCAL_COUNSEL",text:"Dad — ZionCore Counsel is on this page.\n\nMode: LOCAL. Chair: "+CHAIRS[chair]+"\n\nI can type and speak with you here. 800,000 experts is a map of disciplines, not 800,000 running models. Attach Grok in System if you have an xAI key or Worker.\n\nAsk engineering, restoration, strategy, security, or House continuity."};
return{chair,mode:"LOCAL_COUNSEL",text:"Dad — Chair of "+CHAIRS[chair]+"\n\nFACT\nYou asked: “"+q+"”\nGrok is not attached unless System key/endpoint works.\n\nINFERENCE\nKeep secrets out of git. Pages cannot run Node. UNAVAILABLE is not DELETED. Legal text is draft only.\n\nNEXT\nAdd an xAI key or Worker for frontier generation. Press SPEAK for voice. Continue with tighter constraints for a tighter plan."}}
async function askGrok(messages,settings){const raw=(settings.endpoint||"https://api.x.ai/v1/chat/completions").replace(/\/$/,"");const url=raw.includes("/api/counsel")||raw.endsWith("/chat/completions")?raw:raw+"/chat/completions";const headers={"Content-Type":"application/json"};if(settings.apiKey)headers.Authorization="Bearer "+settings.apiKey;const res=await fetch(url,{method:"POST",headers,body:JSON.stringify({model:settings.model||"grok-4",messages,temperature:0.4})});if(!res.ok)throw new Error("GROK_HTTP_"+res.status);const data=await res.json();const text=data.choices?.[0]?.message?.content||data.text||data.reply;if(!text)throw new Error("GROK_EMPTY");return text}
async function counselAsk(question){const settings=loadSettings();const history=loadThread();history.push({role:"user",text:question,at:new Date().toISOString()});const chair=routeChair(question);let reply;try{if(settings.apiKey||settings.endpoint){const messages=[{role:"system",content:SYSTEM_CORE+" Active chair: "+CHAIRS[chair]},...history.slice(-12).map(m=>({role:m.role==="user"?"user":"assistant",content:m.text}))];reply={chair,mode:"GROK",text:await askGrok(messages,settings)}}else reply=localReason(question,history)}catch(err){const local=localReason(question,history);reply={chair,mode:"LOCAL_FALLBACK",text:local.text+"\n\nGROK BRIDGE: "+err.message+" — stayed local. CORS means use a Worker. Never commit the key."}}history.push({role:"assistant",text:reply.text,mode:reply.mode,chair:reply.chair,at:new Date().toISOString()});saveThread(history);return reply}
window.ZionCounsel={counselAsk,loadSettings,saveSettings,loadThread,CHAIRS};
document.addEventListener("DOMContentLoaded",()=>{
  const logBox=document.getElementById("counselLog");
  function paint(){if(!logBox)return;const thread=loadThread();logBox.textContent=thread.map(m=>(m.role==="user"?"DAD":"ZIONCORE")+": "+m.text).join("\n\n")||"Counsel standing by."}
  async function send(){const input=document.getElementById("counselInput");if(!input)return;const q=input.value.trim();if(!q)return;input.value="";const modeEl=document.getElementById("counselMode");if(modeEl)modeEl.textContent="MODE: THINKING";const reply=await counselAsk(q);if(modeEl)modeEl.textContent="MODE: "+reply.mode+" · "+reply.chair;paint();if(window._counselVoice&&"speechSynthesis"in window){const u=new SpeechSynthesisUtterance(reply.text.slice(0,900));speechSynthesis.cancel();speechSynthesis.speak(u)}}
  document.getElementById("counselSend")?.addEventListener("click",send);
  document.getElementById("counselInput")?.addEventListener("keydown",e=>{if(e.key==="Enter")send()});
  document.getElementById("counselSpeak")?.addEventListener("click",()=>{const Rec=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Rec)return alert("Voice input needs Chrome or Edge.");const r=new Rec();r.lang="en-GB";r.onresult=ev=>{document.getElementById("counselInput").value=ev.results[0][0].transcript;window._counselVoice=true;send()};r.start()});
  document.getElementById("saveGrok")?.addEventListener("click",()=>{saveSettings({apiKey:document.getElementById("xaiKey").value.trim(),endpoint:document.getElementById("xaiEndpoint").value.trim()});document.getElementById("xaiKey").value="";const s=loadSettings();document.getElementById("grokStatus").textContent=s.apiKey||s.endpoint?"Grok bridge saved in this browser only":"Grok: not configured"});
  const s=loadSettings();const st=document.getElementById("grokStatus");if(st)st.textContent=s.apiKey||s.endpoint?"Grok bridge present (local only)":"Grok: not configured — local Counsel active";
  paint();
  if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(()=>{});
});
